### ISSUE TITLE
extra c in sonicd

### ISSUE THREAD

**Issue by ccb357** [Tminec/proper-sonic-origins-plus#1]
hi, instead of you typing soniccd folder ,you typed sonicd please fix that

**Comment by Tminec** [comment]
Why do you need that tho? But yeah I can fix it for you, but I am a bit sick rn. I will fix it soon.

**Comment by Tminec** [comment]
I am working on the new update now I will fix everything

**Comment by Tminec** [comment]
**Fixed!**
